baseurl: /starter
permalink: pretty
markdown: rdiscount
prose:
  rooturl: '_posts'
  siteurl: 'http://prose.github.io/starter/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "multiselect"
          label: "Category"
          placeholder: "Choose one or more"
          options:
            - name: "analfabrutos"
              value: "analfabrutos"
            - name: "construções tugas"
              value: "construções tugas"
            - name: "crise, pulhítica"
              value: "crise, pulhítica"
            - name: "ópio do povo"
              value: "ópio do povo"
            - name: "pessoas, animais"
              value: "pessoas, animais"
            - name: "imprensa, tv, pub"
              value: "imprensa, tv, pub"
            - name: "santa sinalização"
              value: "santa sinalização"
            - name: "sobre rodas"
              value: "sobre rodas"
      - name: "layout"
        field:
          element: "select"
          label: "Layout"
          options:
            - name: 'Image'
              value: 'image'
            - name: 'Gallery'
              value: 'gallery'
            - name: 'Video'
              value: 'video'
            - name: 'Quote'
              value: 'quote'
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
            - name: "Pears"
              value: "pears"
            - name: "Mangos"
              value: "mangos"
